version: '2.2'
services:
  archiver:
    image: thzinc/regulations-gov-archiver:${version:-latest}
    build:
      context: .
      dockerfile: ./src/Regulations.Gov.Archiver/Dockerfile
      args:
        version: ${version:-0.0.0-development}
    environment:
      ElasticsearchUrl: http://elasticsearch:9200
      DownloadPath: /data/downloads
    volumes:
      - downloads:/data/downloads
    restart: on-failure
  elasticsearch:
    image: thzinc/elasticsearch:${version:-latest}
    build:
      context: ./src/elasticsearch
      dockerfile: Dockerfile
    environment:
      bootstrap.memory_lock: "true"
      cluster.name: docker-cluster
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200"
    restart: on-failure
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    ports:
      - "5601"
    restart: on-failure
volumes:
  esdata:
    driver: local
  downloads:
    driver: local