version: '2.2'
services:
  archiver:
    image: thzinc/regulations-gov-archiver:${version:-latest}
    build:
      context: .
      dockerfile: ./src/Regulations.Gov.Archiver/Dockerfile
      args:
        version: ${version:-0.0.0-development}
    environment:
      DataGovApiKey: IcuLG6OQnRjH9c0Er2f3JiXFY4E2NcYFxkmBrp3s
      ElasticsearchUrl: http://elasticsearch:9200
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: elasticsearch
    environment:
      bootstrap.memory_lock: "true"
      cluster.name: docker-cluster
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    ports:
      - "5601"
volumes:
  esdata:
    driver: local
