version: '2.2'
services:
  downloader:
    image: thzinc/regulations-gov-downloader:${version:-latest}
    build:
      context: .
      dockerfile: ./src/Regulations.Gov.Downloader/Dockerfile
      args:
        version: ${version:-0.0.0-development}
    environment:
      GoogleKeyJsonPath: /data/key.json
    restart: on-failure
  archiver:
    image: thzinc/regulations-gov-archiver:${version:-latest}
    build:
      context: .
      dockerfile: ./src/Regulations.Gov.Archiver/Dockerfile
      args:
        version: ${version:-0.0.0-development}
    environment:
      ElasticsearchUrl: "http://elasticsearch-ingress:9200,http://elasticsearch-ingest-1:9200,http://elasticsearch-ingest-2:9200"
    restart: on-failure
  elasticsearch-ingress:
    image: thzinc/elasticsearch:${version:-latest}
    build:
      context: ./src/elasticsearch
    environment:
      bootstrap.memory_lock: "true"
      cluster.name: docker-cluster
      node.ingest: "false"
      discovery.zen.ping.unicast.hosts: elasticsearch-ingress,elasticsearch-ingest-1,elasticsearch-ingest-2
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata-ingress:/usr/share/elasticsearch/data
    networks:
      - esnet
    ports:
      - "29200:9200"
    restart: on-failure
  elasticsearch-ingest-1:
    image: thzinc/elasticsearch:${version:-latest}
    build:
      context: ./src/elasticsearch
    environment:
      bootstrap.memory_lock: "true"
      cluster.name: docker-cluster
      node.ingest: "true"
      discovery.zen.ping.unicast.hosts: elasticsearch-ingress,elasticsearch-ingest-1,elasticsearch-ingest-2
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata-ingest-1:/usr/share/elasticsearch/data
    networks:
      - esnet
    restart: on-failure
  elasticsearch-ingest-2:
    image: thzinc/elasticsearch:${version:-latest}
    build:
      context: ./src/elasticsearch
    environment:
      bootstrap.memory_lock: "true"
      cluster.name: docker-cluster
      node.ingest: "true"
      discovery.zen.ping.unicast.hosts: elasticsearch-ingress,elasticsearch-ingest-1,elasticsearch-ingest-2
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata-ingest-2:/usr/share/elasticsearch/data
    networks:
      - esnet
    restart: on-failure
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch-ingress:9200"
    ports:
      - "25601:5601"
    networks:
      - esnet
    restart: on-failure
volumes:
  esdata-ingress:
    driver: local
  esdata-ingest-1:
    driver: local
  esdata-ingest-2:
    driver: local
networks:
  esnet: